language: node_js
node_js:
  - "lts/carbon"
  - "lts/dubnium"
  - "node"
before_install:
  - npm i -g audit-ci && audit-ci -m
install:
  - npm install -g codecov
script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov
