language: node_js
node_js:
  - "lts/carbon"
  - "lts/dubnium"
  - "node"
before_install:
  - npm i -g audit-ci && audit-ci -l
  - npm install
  - npm run clean && npm run build
after_success:
  - npm run coverage
