language: node_js
node_js:
  - "8"
  - "10"
  - "11"
  - "node"
services:
  - docker
before_install:
  - version=`node --version | grep -oP '(?<=v)\d*?(?=\.)'`
  - docker pull node:$version-alpine
  - docker run -d -p 127.0.0.1:80:4567 node:$version-alpine /bin/sh -c "cd /home/node && apk add git"
  - docker run node:$version-alpine /bin/sh -c "git clone https://github.com/Gniar/zencashjs.git && cd zencashjs && npm install && npm run test"
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm run coverage
  - ./cc-test-reporter format-coverage -t lcov .coverage
  - ./cc-test-reporter upload-coverage -r $CC_TEST_REPORTER_ID
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
