language: node_js
node_js:
  - "8"
  - "10"
  - "11"
  - "node"
services:
  - docker
before_install:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker pull `node --version | grep -oP '(?<=v)\d*?(?=\.)'`-alpine
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm run coverage
  - ./cc-test-reporter format-coverage -t lcov .coverage
  - ./cc-test-reporter upload-coverage -r $CC_TEST_REPORTER_ID
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
