language: node_js
node_js:
  - "8"
  - "10"
  - "11"
  - "node"
before_install:
  - if [ "${TRAVIS_PULL_REQUEST}" == "true" ]; then npm i -g audit-ci && audit-ci --report true; fi
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm run coverage
  - ./cc-test-reporter format-coverage -t lcov .coverage
  - ./cc-test-reporter upload-coverage -r $CC_TEST_REPORTER_ID
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
